cylinders:
    cylinder_1:
        rho: 15
        z: [-10, 10]
        points_cnt: 60
        color: 'red'
        size: 8
        marker: 'o'
        direction: 'counterclockwise' # clockwise / counterclockwise

    cylinder_2:
        rho: 15
        z: [-10, 10]
        points_cnt: 60
        color: 'red'
        size: 8
        marker: 'o'
        direction: 'counterclockwise' # clockwise / counterclockwise

animation:
    fps: 60
    save_path: '../cylinder_new2.gif'
    delta_phi: 2 # можно менять скорость вращения за счет изменения угла поворота за один такт
    save: True